apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:ntA7gbbtgzWDJp3NgbQagjpHNbOwl9iPIJ6/vHcmu2/VETfCiTFcGGcnkJhLyp/4sDDHwugwmmYVSlazWpKHIMO/B/z0eysqZnjg0qdfJSOFO8lcSqRNj0cKID5wXoUbHPuHw5XBYiUR4XQM1PZx74haiRYw+WmyIpePToVERBPRXxTL40XcH3SvN4NS79fO3xTsTHwYY1mDnERtqDaLU0f2+e6YmzAHZvFVCfTWRCzL/8BX/mJk3A==,iv:YWtPEMAsSiOpRr3gGbKSDtGAq5hCUvSp7zd1P1FJPB0=,tag:xhUCh7GUKIP+68V8v4E2Rw==,type:str]
sops:
    age:
        - recipient: age1qwffm94jwawu485yut07val9y0rkw0vtgjywudhnhd6kx2zlwv8qrqkj8q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bEhEZXovKytmVHc2RC9x
            a1czNWZWOVVmdHNxNW83Z01FUVUyb3lTRG1FClNFVlcxZzhMcTJETC9TdzJwb0dm
            VVZVeFl5ZEVEdlp2STlEbnZhVXZIWVUKLS0tIGU3RElXekFYN2JFR05HK3ZxRWNY
            YTZhTnZEd3poa0p3QXR3WG5nR0xNb3cKcRGsm/07hv2E3j7FNkfH/2KWh9oQCkY7
            eMSnmqkNXttD6EinkzMjI2OqpE+tEWOth+PMRklQMndMNWV2gEgfng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T02:01:04Z"
    mac: ENC[AES256_GCM,data:2oq5iHESMx060Iid9iy4rho/rZGRUU9vWVq3jcgE+Nk2H1re+Z4NV+w9XyoG4apTSiEmcqcHpyAke/dw3zajMW1OlOG6C7fuvd4QULx89PqgozvWCNdfT8OudEkfopDyADPTsj+1xEUgt27AC8HlUbr6AnUQsiawfQd/D4Cjqkw=,iv:IrUVXZ8pAYi4/yADhFr2aqvUGXrBedmjoENg770ugYU=,tag:fo18fAziE0Voa6fKILU8bQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
