apiVersion: v1
kind: Namespace
metadata:
  name: home
---
apiVersion: v1
data:
  mosquitto.conf: |-
    persistence true
    persistence_location /mosquitto/data/
    log_dest stdout
    listener 1883
    listener 9090
    protocol websockets
    allow_anonymous true
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: home
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    io.cilium/lb-ipam-ips: private
  name: mqtt
  namespace: home
spec:
  ipFamilies:
  - IPv4
  - IPv6
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: mqtt
    port: 1883
    protocol: TCP
  - name: mqtt-ws
    port: 8001
    protocol: TCP
  selector:
    app: mosquitto
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    io.cilium/lb-ipam-ips: private
  name: zigbee2mqtt
  namespace: home
spec:
  ipFamilies:
  - IPv4
  - IPv6
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: web
    port: 8080
    protocol: TCP
  selector:
    app: zigbee2mqtt
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto
  namespace: home
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt
  namespace: home
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mosquitto
  name: mosquitto
  namespace: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - image: eclipse-mosquitto:2.0.22
        name: mosquitto
        ports:
        - containerPort: 1883
          name: mqtt
        - containerPort: 8001
          name: mqtt-ws
        resources:
          limits:
            cpu: 50m
            memory: 64Mi
          requests:
            cpu: 10m
            memory: 32Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /mosquitto/config
          name: config
        - mountPath: /mosquitto
          name: data
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      volumes:
      - configMap:
          defaultMode: 420
          name: mosquitto-config
        name: config
      - name: data
        persistentVolumeClaim:
          claimName: mosquitto
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zigbee2mqtt
  name: zigbee2mqtt
  namespace: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      containers:
      - image: koenkk/zigbee2mqtt:2.8.0
        name: zigbee2mqtt
        ports:
        - containerPort: 8080
          name: web
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /app/data
          name: config
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: zigbee2mqtt
