apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: magi-lb-advertisements
spec:
  advertisements:
    - advertisementType: Service
      service:
        addresses:
          - LoadBalancerIP
      selector:
        matchLabels: {}
