apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: public
spec:
  blocks:
    - cidr: "fd7a:6e5b:cafe:10:1::1/120"
    - cidr: "10.1.1.0/24"
---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: private
spec:
  blocks:
    - cidr: "fd7a:6e5b:cafe:10:2::1/120"
    - cidr: "10.1.2.0/24"
