apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cameras
resources:
  - namespace.yaml
  - cameras-nad.yaml
  - ../../../apps/frigate
 
patches:
  - path: patches/frigate.yaml
