apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mrakaki
resources:
  - namespace.yaml
  - ../../../apps/mrakaki
 
patches:
  - path: patches/configuration-service.yaml
  - path: patches/authentication-service.yaml
  - path: patches/buyback-service.yaml
  - path: patches/universe-service.yaml
  