apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: iot
  namespace: home
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "bond0.20",
      "mode": "bridge",
      "ipam": {
        "type": "whereabouts",
        "range": "172.16.20.0/24",
        "range_start": "172.16.20.200",
        "range_end": "172.16.20.250",
        "gateway": "172.16.20.1"
      }
    }
