cluster:
  allowSchedulingOnControlPlanes: true
  network:
    cni:
      name: none
    podSubnets:
      - 10.41.0.0/16
      - fd7a:41::/48
    serviceSubnets:
      - 10.42.0.0/16
      - fd7a:42::/112
  proxy:
    disabled: true

machine:
  type: controlplane
  kubelet:
    extraMounts:
      - destination: /var/mnt/longhorn-disk1
        type: bind
        source: /var/mnt/longhorn-disk1
        options:
          - bind
          - rshared
          - rw
      - destination: /var/mnt/longhorn-disk2
        type: bind
        source: /var/mnt/longhorn-disk2
        options:
          - bind
          - rshared
          - rw
  network:
    nameservers:
      - 10.1.0.1
      - fd7a:6e5b:cafe:10::1
    interfaces:
      - interface: bond0
        vlans:
          - vlanId: 15
            dhcp: false
            addresses: []
          - vlanId: 20
            dhcp: false
            addresses: []
          - vlanId: 25
            dhcp: false
            addresses: []
  install:
    bootloader: true
    wipe: true
    image: factory.talos.dev/installer/fd5420096bc116ef7eb6952e8ea7ef83efa4d515c7cf98079501cc2aabda85c5:v1.12.5
  kernel:
    modules:
      - name: nvme_tcp
      - name: vfio_pci
      - name: gasket
      - name: apex
  sysctls:
    vm.nr_hugepages: "1024"

---
apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: nut-client
configFiles:
  - content: |-
      MONITOR forza@10.1.0.79 1 observer OBSERVER_PASSWORD_HERE secondary
      SHUTDOWNCMD "/sbin/poweroff"
      POWERDOWNFLAG /var/run/nut.powerdown
    mountPath: /usr/local/etc/nut/upsmon.conf
