machine:
  kubelet:
    nodeIP:
      validSubnets:
        - 10.255.100.0/24
  network:
    interfaces:
      - interface: bond0
        dhcp: false
        bond:
          mode: 802.3ad
          lacpRate: fast
          miimon: 100
          interfaces:
            - eth0
            - eth1
        addresses:
          - fd7a:6e5b:cafe:10::8/64
          - 10.1.0.8/22
        routes:
          - network: ::/0
            gateway: fd7a:6e5b:cafe:10::1
          - network: 0.0.0.0/0
            gateway: 10.1.0.1
      - interface: eth2
        dhcp: false
        addresses:
          - fd7a:6e5b:beff::8/64
          - 10.255.100.8/24
      - interface: eth3
        dhcp: false
        addresses:
          - fd7a:6e5b:befe::8/64
          - 10.255.200.8/24
  install:
    diskSelector:
      serial: 2M322L1CBHHE
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: melchior
auto: off
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: longhorn-disk1
volumeType: disk
provisioning:
  diskSelector:
    match: disk.serial == "50026B72836AC7FD"
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: longhorn-disk2
volumeType: disk
provisioning:
  diskSelector:
    match: disk.serial == "TPBF2509080010200763"