apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: immich-ml
spec:
  selector:
    matchLabels:
      app: immich-ml
  serviceName: immich-ml
  replicas: 1
  template:
    metadata:
      labels:
        app: immich-ml
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 10
      containers:
        - name: immich-ml
          image: ghcr.io/immich-app/immich-machine-learning:v2.5.6 # {"$imagepolicy": "flux-system:immich-ml"}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          env:
            - name: IMMICH_PORT
              value: "3003"
          ports:
            - containerPort: 3003
              name: http
          volumeMounts:
            - name: immich-models
              mountPath: /cache
          resources:
            requests:
              cpu: 750m
              memory: 1.5Gi
            limits:
              cpu: 1000m
              memory: 2Gi
  volumeClaimTemplates:
    - metadata:
        name: immich-models
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
