apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: immich
spec:
  selector:
    matchLabels:
      app: immich
  serviceName: immich
  replicas: 1
  template:
    metadata:
      labels:
        app: immich
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 10
      containers:
      - name: immich
        image: ghcr.io/immich-app/immich-server:v2.5.6 # {"$imagepolicy": "flux-system:immich"}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        env:
        - name: DB_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: immich-postgres-config
              key: host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: immich-postgres-config
              key: port
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: immich-postgres-config
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: immich-postgres-config
              key: password
        - name: DB_DATABASE_NAME
          value: immich
        - name: IMMICH_PORT
          value: "2283"
        - name: REDIS_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: immich-redis-config
              key: host
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: immich-redis-config
              key: port
        - name: MACHINE_LEARNING_PORT
          value: "3003"
        - name: MACHINE_LEARNING_HOST
          value: immich-machine-learning
        - name: TZ
          value: America/Costa_Rica
        ports:
        - name: http
          containerPort: 2283
        volumeMounts:
        - mountPath: /data
          name: data
        resources:
          requests:
            cpu: 2
            memory: 8Gi
          limits:
            cpu: 2500m
            memory: 8Gi
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 900Gi
