apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infra-controllers.yaml
  - infra-configs.yaml
  - namespace-databases.yaml
  - namespace-sspti.yaml
  - namespace-tunnels.yaml