apiVersion: v1
kind: Service
metadata:
  name: esphome
spec:
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esphome
spec:
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: iot
