apiVersion: v1
kind: Service
metadata:
  name: immich
  labels:
    lb-pool: public
spec:
  externalTrafficPolicy: Local
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
---
apiVersion: v1
kind: Service
metadata:
  name: immich-machine-learning
spec:
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
