apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: frigate
spec:
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: cameras
    spec:
       affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: feature.node.kubernetes.io/coral-tpu.installed
                  operator: In
                  values:
                    - "true"
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: media
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 256Gi