apiVersion: v1
kind: Secret
metadata:
    name: mariadb-credentials
type: Opaque
stringData:
    root-password: ENC[AES256_GCM,data:+Pb6if/cbDZra45/,iv:kE/NJpnkNrX6skV/lvWIS/PdVDkD1DrVEzf5k8HM60U=,tag:A7gnCSEuOOTy+FJMG3+5ig==,type:str]
sops:
    age:
        - recipient: age1qwffm94jwawu485yut07val9y0rkw0vtgjywudhnhd6kx2zlwv8qrqkj8q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dyt0bWlUWFoyaHhMcFJt
            TTJyNlpzalNKRlFoV0NHbnFYTC90TkhiWVdJCks1ckNiY1V2M0JubElUamQ0OWx3
            a2dlcklXM2JOYzBaS2NxdGJDaVhQZU0KLS0tIHFWUHhqWWxKdzZ6amIzd0lGd29G
            ZWZneDZYRHBwZW93NTlSMnRGcFYzbGsKMiD3HOktf5gnSTk/BMcgN7Cfa/oov+Xj
            rXTEdwlj2D2+Nb5zSLyzOzn/Rhm7zfSR15Sc6EpH0eUVjnMFy3Vy9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T00:24:44Z"
    mac: ENC[AES256_GCM,data:reRkkA+B5Jy45y8WSV0Uoqge8madpHcDcpYZw3OtiLn4E/bnqogeh/+v4+X1XcxF8b2RPqZu6xh7zaUQQsN3ZXJHh7emnqobKmvmyno1NyDwHzt2JUeV978kSseago6RKiZRsAvEQTkzyfg7h9/ws3I5fZ5FMCpy+dXz4qtVqjE=,iv:8RHamYXMAeAkZjttPw5lH/JTKGNUb8dJQDWnxfNNgkU=,tag:n4gcUMWQXhSfxTB3GiYucw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
