apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:Cg5G4fVwr1yH+P3W6m6sLPxj3jpRHwceNU8fSO15ig==,iv:JIfQTTOkqeaNl2Z5L7zXEPeo7+m0+sIh7n1AB5o/Xus=,tag:wSdvurrTahj1CnQgg/13IA==,type:str]
    user: ENC[AES256_GCM,data:hRUhMIhDHsw=,iv:HC4ZM6gcXK8YtUqbiZ8ptt0djZpj/APPBvMsgiB3W+A=,tag:Qnv0236eL3rHcAGgZn/YZw==,type:str]
sops:
    age:
        - recipient: age1qwffm94jwawu485yut07val9y0rkw0vtgjywudhnhd6kx2zlwv8qrqkj8q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNc1djRkJlTHZVb3EzMlhC
            aTRTLzFKZkkwdzZyVmZzS2Q1L0I1RnZxTW1BCmhiSHdyTm43N0EvR3JxNGxBS3Jw
            TG5QaU5DUG95S2NFcS85OE5VN292aFUKLS0tIEx3blhyd0FIR1ZHNjdXNm9hc24z
            bzc4ZGNlbEhQRnhJTFdma2htaTFQY1UK8kmPVGD8TZ74JaQBNjs9eRKVgAMe9u5W
            KkcE5nYqai/9fBNasEJ+2LVlJlGweTFb9RPOAq/PDlih6PjcFgG4XQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T04:17:18Z"
    mac: ENC[AES256_GCM,data:UzU/FWcecpBFr9jITYk/Vuc3YC++69b+QSWNoaNGojObQa9owrWc2sbGb7SCh99DB/mpkSuMqJIe0H33Oqb2LIEbFmIAFXIatetiZz1dUpdTR+7vpPWUxoe0+10lWYFjZNoxaimkq53hQ0IL3KB6T+UUeTEAFTJJOohOAKzpgMc=,iv:xHrwd71T4Q73gg1Fd73b8cY6rL149dJK4UBz2VOmEBA=,tag:Gip4mtbczZBu0rjbb9n9Qw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
